version: "3.9"

services:
  frontend:
    build: ./PersonalBlogFrontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - app-network

  backend:
    build: ./PersonalBlogBackend
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - PRODUCTION_URL=${PRODUCTION_URL}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # - "443:443" # For future SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./ssl:/etc/nginx/ssl # For future SSL certificates
    depends_on:
      - frontend
      - backend
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# to build and run the containers, use:
# docker-compose up --build